name:                advent-of-code-year2022
version:             0.1.0.0
github:              "joseedil/advent-of-code-year2022"
license:             BSD3
author:              "Edil Medeiros"
maintainer:          "jose.edil@gmail.com"
copyright:           "2022 Edil Medeiros"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/joseedil/advent-of-code-year2022#readme>

dependencies:
- base >= 4.7 && < 5
- text
- vector

# ghc-options:
# - -Wall
# - -Wcompat
# - -Widentities
# - -Wincomplete-record-updates
# - -Wincomplete-uni-patterns
# - -Wmissing-export-lists
# - -Wmissing-home-modules
# - -Wpartial-fields
# - -Wredundant-constraints

library:
  source-dirs: src
  default-extensions:
    - OverloadedStrings

executables:
  advent-of-code-year2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-year2022

tests:
  advent-of-code-year2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-of-code-year2022
